# Generated by Django 4.2.13 on 2025-06-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='puppies',
            new_name='puppy',
        ),
    ]
